// @ts-nocheck
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {Routes} from '@angular/router';
import {NgDocDemoAssets, NgDocPageComponent, NgDocRootPage} from '@ng-doc/app';
import {isRoute, NgDocPage, NgDocPageType} from '@ng-doc/core';
import entry from '../../../../../../../../../src/app/categories/initializer/features/with-initialize-state/ng-doc.page';
import {PLAYGROUND_COMPONENTS, PLAYGROUND_PROVIDERS} from '../playgrounds';
import demoAssets from '../demo-assets';

const pageContent: string = `<p class="ngde">Imported from <code class="ngde">@ngmd/utils/initializer</code></p><hr class="ngde"><h2 id="description" href="initializer/features/with-initialize-state" headinglink="true" class="ngde">Description<ng-doc-heading-anchor class="ng-doc-anchor ngde" anchor="description"></ng-doc-heading-anchor></h2><p class="ngde"><em class="ngde">Feature function</em> that defines the strategy for loading a configuration file into the <em class="ngde">InitializeState</em> object.</p><p class="ngde"><strong class="ngde">Interface</strong></p><pre class="shiki shiki-themes github-light ayu-dark" style="background-color:#fff;--shiki-dark-bg:#0b0e14;color:#24292e;--shiki-dark:#bfbdb6" tabindex="0"><code class="language-ts"><span class="line"><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">function</span><span style="color:#6F42C1;--shiki-dark:#FFB454" class="ngde"> <a href="/initializer/features/with-initialize-state#withinitializestate" class="ng-doc-code-anchor ngde">withInitializeState</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">()</span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde">:</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> <a href="/initializer/features/with-initialize-state" class="ng-doc-code-anchor ngde">InitializeStateFeature</a></span></span></code></pre><p class="ngde"><strong class="ngde">Usage</strong></p><p class="ngde">A detailed integration guide is described <a href="/initializer/introduction#from-angular-18-and-above" class="ngde">here</a></p><pre class="shiki shiki-themes github-light ayu-dark" style="background-color:#fff;--shiki-dark-bg:#0b0e14;color:#24292e;--shiki-dark:#bfbdb6" tabindex="0" name="src/app/app.config.ts"><code class="language-ts"><span class="line"><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">import</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde"> \{</span></span>
<span class="line"><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">  <a href="/initializer/introduction#provideutilsinitializer" class="ng-doc-code-anchor ngde">provideUtilsInitializer</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span></span>
<span class="line"><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">  <a href="/initializer/features/with-initialize-state#withinitializestate" class="ng-doc-code-anchor ngde">withInitializeState</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span></span>
<span class="line"><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">  <a href="/initializer/features/with-initialize-state#initializestate" class="ng-doc-code-anchor ngde">InitializeState</a></span></span>
<span class="line"><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">\} </span><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde"><a href="https://rxjs.dev/api/index/function/from" class="ng-doc-code-anchor ngde" ngDocTooltip="External link the RxJS documentation.">from</a></span><span style="color:#032F62;--shiki-dark:#AAD94C" class="ngde"> '@ngmd/utils/initializer'</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">;</span></span>
<span class="line"><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">import</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde"> \{ <a href="/interceptor/introduction#provideutilsinterceptor" class="ng-doc-code-anchor ngde">provideUtilsInterceptor</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde"> <a href="/interceptor/features/with-tags-urls-map#withtagsurlsmap" class="ng-doc-code-anchor ngde">withTagsUrlsMap</a> \} </span><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde"><a href="https://rxjs.dev/api/index/function/from" class="ng-doc-code-anchor ngde" ngDocTooltip="External link the RxJS documentation.">from</a></span><span style="color:#032F62;--shiki-dark:#AAD94C" class="ngde"> '@ngmd/utils/interceptor'</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">;</span></span>
<span class="line"><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">import</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde"> \{ environment</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde"> IConfig \} </span><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde"><a href="https://rxjs.dev/api/index/function/from" class="ng-doc-code-anchor ngde" ngDocTooltip="External link the RxJS documentation.">from</a></span><span style="color:#032F62;--shiki-dark:#AAD94C" class="ngde"> '@env'</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">export</span><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde"> const</span><span style="color:#005CC5;--shiki-dark:#BFBDB6" class="ngde"> AppConfig</span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde">:</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> <a href="https://angular.dev/api/platform-browser/ApplicationConfig" class="ng-doc-code-anchor ngde" ngDocTooltip="External link the Angular documentation.">ApplicationConfig</a></span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde"> =</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde"> \{</span></span>
<span class="line"><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">  providers</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">:</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde"> [</span></span>
<span class="line"><span style="color:#6F42C1;--shiki-dark:#FFB454" class="ngde">    <a href="/initializer/introduction#provideutilsinitializer" class="ng-doc-code-anchor ngde">provideUtilsInitializer</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">(environment</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span><span style="color:#6F42C1;--shiki-dark:#FFB454" class="ngde"> <a href="/initializer/features/with-initialize-state#withinitializestate" class="ng-doc-code-anchor ngde">withInitializeState</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">())</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span></span>
<span class="line"><span style="color:#6F42C1;--shiki-dark:#FFB454" class="ngde">    <a href="/interceptor/introduction#provideutilsinterceptor" class="ng-doc-code-anchor ngde">provideUtilsInterceptor</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">(</span></span>
<span class="line"><span style="color:#6F42C1;--shiki-dark:#FFB454" class="ngde">      <a href="/interceptor/features/with-tags-urls-map#withtagsurlsmap" class="ng-doc-code-anchor ngde">withTagsUrlsMap</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">(() </span><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">=></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde"> \{</span></span>
<span class="line"><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">        const</span><span style="color:#005CC5;--shiki-dark:#BFBDB6" class="ngde"> initializeState</span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde">:</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> <a href="/initializer/features/with-initialize-state#initializestate" class="ng-doc-code-anchor ngde">InitializeState</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">&#x3C;</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde">IConfig</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">> </span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde">=</span><span style="color:#6F42C1;--shiki-dark:#FFB454" class="ngde"> <a href="https://angular.dev/api/core/testing/inject" class="ng-doc-code-anchor ngde" ngDocTooltip="External link the Angular documentation.">inject</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">(<a href="/initializer/features/with-initialize-state#initializestate" class="ng-doc-code-anchor ngde">InitializeState</a>)</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">;</span></span>
<span class="line"><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">        const</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde"> \{ </span><span style="color:#005CC5;--shiki-dark:#BFBDB6" class="ngde">API_HOST</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span><span style="color:#005CC5;--shiki-dark:#BFBDB6" class="ngde"> WS_HOST</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde"> \}</span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde">:</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> IConfig</span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde"> =</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde"> initializeState</span><span style="color:#24292E;--shiki-dark:#F29668" class="ngde">.</span><span style="color:#6F42C1;--shiki-dark:#FFB454" class="ngde"><a href="https://rxjs.dev/api/index/const/config" class="ng-doc-code-anchor ngde" ngDocTooltip="External link the RxJS documentation.">config</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">()</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">        return</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde"> \{ </span><span style="color:#032F62;--shiki-dark:#AAD94C" class="ngde">'@'</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">:</span><span style="color:#005CC5;--shiki-dark:#BFBDB6" class="ngde"> API_HOST</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span><span style="color:#032F62;--shiki-dark:#AAD94C" class="ngde"> '@ws'</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">:</span><span style="color:#005CC5;--shiki-dark:#BFBDB6" class="ngde"> WS_HOST</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde"> \}</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">;</span></span>
<span class="line"><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">      \})</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span></span>
<span class="line"><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">    )</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span></span>
<span class="line"><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">  ]</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span></span>
<span class="line"><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">\}</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">;</span></span></code></pre><h2 id="initializestate" href="initializer/features/with-initialize-state" headinglink="true" class="ngde">InitializeState<ng-doc-heading-anchor class="ng-doc-anchor ngde" anchor="initializestate"></ng-doc-heading-anchor></h2><p class="ngde">Class that stores the configuration file and loading status fields:</p><p class="ngde"><strong class="ngde">Interface</strong></p><pre class="shiki shiki-themes github-light ayu-dark" style="background-color:#fff;--shiki-dark-bg:#0b0e14;color:#24292e;--shiki-dark:#bfbdb6" tabindex="0"><code class="language-ts"><span class="line"><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">class</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> <a href="/initializer/features/with-initialize-state#initializestate" class="ng-doc-code-anchor ngde">InitializeState</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">&#x3C;</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde">T</span><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde"> extends</span><span style="color:#005CC5;--shiki-dark:#39BAE6" class="ngde"> object</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">> \{</span></span>
<span class="line"><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">  public</span><span style="color:#E36209;--shiki-dark:#BFBDB6" class="ngde"> <a href="https://rxjs.dev/api/index/const/config" class="ng-doc-code-anchor ngde" ngDocTooltip="External link the RxJS documentation.">config</a></span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde">:</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> <a href="https://angular.dev/api/core/WritableSignal" class="ng-doc-code-anchor ngde" ngDocTooltip="External link the Angular documentation.">WritableSignal</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">&#x3C;</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde">T</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">></span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">;</span></span>
<span class="line"><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">  public</span><span style="color:#E36209;--shiki-dark:#BFBDB6" class="ngde"> loaded</span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde">:</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> <a href="https://angular.dev/api/core/Signal" class="ng-doc-code-anchor ngde" ngDocTooltip="External link the Angular documentation.">Signal</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">&#x3C;</span><span style="color:#005CC5;--shiki-dark:#39BAE6" class="ngde">boolean</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">></span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">;</span></span>
<span class="line"><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">  public</span><span style="color:#E36209;--shiki-dark:#BFBDB6" class="ngde"> whenLoaded$</span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde">:</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> <a href="https://rxjs.dev/api/index/class/Observable" class="ng-doc-code-anchor ngde" ngDocTooltip="External link the RxJS documentation.">Observable</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">&#x3C;</span><span style="color:#005CC5;--shiki-dark:#39BAE6" class="ngde">boolean</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">></span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">;</span></span>
<span class="line"><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">\}</span></span></code></pre><p class="ngde"><strong class="ngde">Description</strong></p><div class="ng-doc-table-wrapper ngde"><table class="ngde"><thead class="ngde"><tr class="ngde"><th class="ngde">Name</th><th class="ngde">Type</th><th class="ngde">Default</th><th class="ngde">Description</th></tr></thead><tbody class="ngde"><tr class="ngde"><td class="ngde"><strong class="ngde">config</strong></td><td class="ngde"><code class="ngde">T extends object</code></td><td class="ngde"><code class="ngde">null</code></td><td class="ngde">Configuration file object</td></tr><tr class="ngde"><td class="ngde"><strong class="ngde">loaded</strong></td><td class="ngde"><code class="ngde ng-doc-code-with-link"><a href="https://angular.dev/api/core/Signal" class="ng-doc-code-anchor ngde" ngDocTooltip="External link the Angular documentation.">Signal</a>&#x3C;boolean></code></td><td class="ngde"><code class="ngde">false</code></td><td class="ngde">Configuration file loading status</td></tr><tr class="ngde"><td class="ngde"><strong class="ngde">whenLoaded$</strong></td><td class="ngde"><code class="ngde ng-doc-code-with-link"><a href="https://angular.dev/api/core/Signal" class="ng-doc-code-anchor ngde" ngDocTooltip="External link the Angular documentation.">Signal</a>&#x3C;boolean></code></td><td class="ngde"><code class="ngde">false</code></td><td class="ngde">Emits <code class="ngde">true</code> when the configuration file is loaded (when subscribed).</td></tr></tbody></table></div>`

@Component({
  selector: 'ng-doc-page-um87memo',
  template: `<ng-doc-page></ng-doc-page>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    NgDocPageComponent,
    ...PLAYGROUND_COMPONENTS,
  ],
  providers: [
    {provide: NgDocRootPage, useExisting: PageComponent},
    PLAYGROUND_PROVIDERS,
    (entry.providers ?? []),
  ],
})
export class PageComponent extends NgDocRootPage {
  readonly pageType: NgDocPageType = 'guide';
  readonly pageContent: string = pageContent;
  readonly page?: NgDocPage = entry;
  readonly demoAssets: NgDocDemoAssets = demoAssets;

  constructor() {
    super();
  }
}

const routes: Routes = [{
  ...(isRoute(entry.route) ? entry.route : {}),
  path: '',
  component: PageComponent,
  title: `withInitializeState`,
}]

export default routes;

