// @ts-nocheck
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {Routes} from '@angular/router';
import {NgDocDemoAssets, NgDocPageComponent, NgDocRootPage} from '@ng-doc/app';
import {isRoute, NgDocPage, NgDocPageType} from '@ng-doc/core';
import entry from '../../../../../../../../../../src/app/categories/http/resources/pages/use-put/ng-doc.page';
import {PLAYGROUND_COMPONENTS, PLAYGROUND_PROVIDERS} from '../playgrounds';
import demoAssets from '../demo-assets';

const pageContent: string = `<p class="ngde">Imported from <code class="ngde">@ngmd/utils/http</code></p><hr class="ngde"><h2 id="description" href="http/resources/use-put" headinglink="true" class="ngde">Description<ng-doc-heading-anchor class="ng-doc-anchor ngde" anchor="description"></ng-doc-heading-anchor></h2><p class="ngde">This page describes how to create a <strong class="ngde">[PUT]</strong> request.</p><h2 id="useput" href="http/resources/use-put" headinglink="true" class="ngde">usePut<ng-doc-heading-anchor class="ng-doc-anchor ngde" anchor="useput"></ng-doc-heading-anchor></h2><p class="ngde">Function for creating a <strong class="ngde">[PUT]</strong> request</p><p class="ngde"><strong class="ngde">Interface</strong></p><pre class="shiki shiki-themes github-light ayu-dark" style="background-color:#fff;--shiki-dark-bg:#0b0e14;color:#24292e;--shiki-dark:#bfbdb6" tabindex="0"><code class="language-ts"><span class="line"><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">function</span><span style="color:#6F42C1;--shiki-dark:#FFB454" class="ngde"> <a href="/http/resources/use-put#useput" class="ng-doc-code-anchor ngde">usePut</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">&#x3C;</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde">Body</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> Response</span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde"> =</span><span style="color:#005CC5;--shiki-dark:#39BAE6" class="ngde"> null</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> Options</span><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde"> extends</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> <a href="/http/classes/crud-request#urloptions" class="ng-doc-code-anchor ngde">UrlOptions</a></span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde"> =</span><span style="color:#005CC5;--shiki-dark:#39BAE6" class="ngde"> null</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">>(</span></span>
<span class="line"><span style="color:#E36209;--shiki-dark:#D2A6FF" class="ngde">  meta</span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde">:</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> <a href="/http/classes/api-request#requestmeta" class="ng-doc-code-anchor ngde">RequestMeta</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">&#x3C;</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde">Response</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">> </span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde">|</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> <a href="/http/classes/crud-request#requesturl" class="ng-doc-code-anchor ngde">RequestUrl</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">&#x3C;</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"><a href="/http/classes/crud-request#urloptions" class="ng-doc-code-anchor ngde">UrlOptions</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">></span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span></span>
<span class="line"><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">)</span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde">:</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> <a href="/http/resources/use-put#putrequest" class="ng-doc-code-anchor ngde">PutRequest</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">&#x3C;</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde">Body</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> Response</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> Options</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">></span></span></code></pre><h2 id="putrequest" href="http/resources/use-put" headinglink="true" class="ngde">PutRequest<ng-doc-heading-anchor class="ng-doc-anchor ngde" anchor="putrequest"></ng-doc-heading-anchor></h2><p class="ngde">Class for <strong class="ngde">[PUT]</strong> requests</p><p class="ngde"><strong class="ngde">Interface</strong></p><pre class="shiki shiki-themes github-light ayu-dark" style="background-color:#fff;--shiki-dark-bg:#0b0e14;color:#24292e;--shiki-dark:#bfbdb6" tabindex="0"><code class="language-ts"><span class="line"><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">class</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> <a href="/http/resources/use-put#putrequest" class="ng-doc-code-anchor ngde">PutRequest</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">&#x3C;</span></span>
<span class="line"><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde">  Body</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span></span>
<span class="line"><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde">  Response</span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde"> =</span><span style="color:#005CC5;--shiki-dark:#39BAE6" class="ngde"> null</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span></span>
<span class="line"><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde">  Options</span><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde"> extends</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> <a href="/http/classes/crud-request#urloptions" class="ng-doc-code-anchor ngde">UrlOptions</a></span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde"> =</span><span style="color:#005CC5;--shiki-dark:#39BAE6" class="ngde"> null</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span></span>
<span class="line"><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">> </span><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">extends</span><span style="color:#6F42C1;--shiki-dark:#39BAE6" class="ngde"> <a href="/http/classes/crud-request#crudrequest" class="ng-doc-code-anchor ngde">CrudRequest</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">&#x3C;</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde">Response</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">> \{</span></span>
<span class="line"></span>
<span class="line"><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">  public</span><span style="color:#6F42C1;--shiki-dark:#FFB454" class="ngde"> request</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">(</span><span style="color:#E36209;--shiki-dark:#D2A6FF" class="ngde">body</span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde">:</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> Body</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span><span style="color:#E36209;--shiki-dark:#D2A6FF" class="ngde"> opts</span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde">?:</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> <a href="/http/resources/use-put#putrequestoptions" class="ng-doc-code-anchor ngde">PutRequestOptions</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">&#x3C;</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde">Options</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">>)</span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde">:</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> <a href="https://rxjs.dev/api/index/class/Observable" class="ng-doc-code-anchor ngde" ngDocTooltip="External link the RxJS documentation.">Observable</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">&#x3C;</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde">Response</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">></span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#D73A49;--shiki-dark:#FF8F40" class="ngde">  public</span><span style="color:#6F42C1;--shiki-dark:#FFB454" class="ngde"> send</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">(</span><span style="color:#E36209;--shiki-dark:#D2A6FF" class="ngde">body</span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde">:</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> Body</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span><span style="color:#E36209;--shiki-dark:#D2A6FF" class="ngde"> opts</span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde">?:</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> <a href="/http/resources/use-put#putsendoptions" class="ng-doc-code-anchor ngde">PutSendOptions</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">&#x3C;</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde">Response</span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">,</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> Options</span><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">>)</span><span style="color:#D73A49;--shiki-dark:#F29668" class="ngde">:</span><span style="color:#6F42C1;--shiki-dark:#59C2FF" class="ngde"> <a href="https://rxjs.dev/api/index/class/Subscription" class="ng-doc-code-anchor ngde" ngDocTooltip="External link the RxJS documentation.">Subscription</a></span><span style="color:#24292E;--shiki-dark:#BFBDB6B3" class="ngde">;</span></span>
<span class="line"><span style="color:#24292E;--shiki-dark:#BFBDB6" class="ngde">\}</span></span></code></pre><h2 id="types" href="http/resources/use-put" headinglink="true" class="ngde">Types<ng-doc-heading-anchor class="ng-doc-anchor ngde" anchor="types"></ng-doc-heading-anchor></h2><h3 id="putrequestoptions" href="http/resources/use-put" headinglink="true" class="ngde">PutRequestOptions<ng-doc-heading-anchor class="ng-doc-anchor ngde" anchor="putrequestoptions"></ng-doc-heading-anchor></h3><p class="ngde">Interface and field descriptions <a href="/http/classes/api-request#httprequestoptions" class="ngde">here</a></p><h3 id="putsendoptions" href="http/resources/use-put" headinglink="true" class="ngde">PutSendOptions<ng-doc-heading-anchor class="ng-doc-anchor ngde" anchor="putsendoptions"></ng-doc-heading-anchor></h3><p class="ngde">Interface and field descriptions <a href="/http/classes/api-request#sendrequestoptions" class="ngde">here</a></p>`

@Component({
  selector: 'ng-doc-page-75b1redm',
  template: `<ng-doc-page></ng-doc-page>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    NgDocPageComponent,
    ...PLAYGROUND_COMPONENTS,
  ],
  providers: [
    {provide: NgDocRootPage, useExisting: PageComponent},
    PLAYGROUND_PROVIDERS,
    (entry.providers ?? []),
  ],
})
export class PageComponent extends NgDocRootPage {
  readonly pageType: NgDocPageType = 'guide';
  readonly pageContent: string = pageContent;
  readonly page?: NgDocPage = entry;
  readonly demoAssets: NgDocDemoAssets = demoAssets;

  constructor() {
    super();
  }
}

const routes: Routes = [{
  ...(isRoute(entry.route) ? entry.route : {}),
  path: '',
  component: PageComponent,
  title: `usePut`,
}]

export default routes;

